name: "bt2mqtt to Hassio"
description: "bt2mqtt to Hassio"
version: "1.0.6"
slug: "bt2mqtt"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  beer: true
  wine: true
  liquor: false
  name: "world"
  year: 2017
schema:
  beer: bool
  wine: bool
  liquor: bool
  name: str
  year: int
